graph [
node [id 0 label "C"]
node [id 1 label "C"]
node [id 2 label "H"]
node [id 3 label "H"]
node [id 4 label "H"]
node [id 5 label "H"]
node [id 6 label "H"]
node [id 7 label "H"]
edge [source 0 target 1 label "-"]
edge [source 0 target 2 label "-"]
edge [source 0 target 3 label "-"]
edge [source 0 target 4 label "-"]
edge [source 1 target 5 label "-"]
edge [source 1 target 6 label "-"]
edge [source 1 target 7 label "-"]
]
